### ISSUE TITLE
Create Compatibility

### ISSUE THREAD

**Issue by KintsugiKitten** [Mrthomas20121-Mods/Rechiseled-Ecosphere#1]
I've been playing with Create a lot lately, mostly the new Full Steam update. And while I would appreciate an update to 1.18.2, I understand that updating can be annoying, so that's not what I'm here for. I'm here because there are some stone types in Create that I think could make very good templates for chisel designs, and I wanted to suggest that you take some time to go over them and see what you can do. And if you need any help with the textures, you can let me know! I'm more than happy to do anywhere from a few to all of the Create chisel textures!

**Comment by Mrthomas20121** [comment]
create doesn't have compat because its stones palette does not looks good.

**Comment by Mrthomas20121** [comment]
![2022-01-24_15 52 48](https://user-images.githubusercontent.com/34064092/182323189-9584edd8-a2cf-4a38-8be6-5e8ffa0be1df.png)
