### ISSUE TITLE
Excessive log spam caused by this mod

### ISSUE THREAD

**Issue by Gronglegrowth** [Mrthomas20121-Mods/Rechiseled-Ecosphere#3]
Whenever the game tries to load this mod's recipes and loot tables that use blocks that don't exist (because the required mods are missing) it prints errors about that in the game log, resulting in huge file sizes. For example I don't have Tropicraft installed and there are 720 instances of the word tropicraft mentioned in a log my game produced which is 1,522,306 lines long, and is 130mb in size, and I had only had the game open for about ten minutes. I can't attach said log here due to its size. This is probably a minor issue as it doesn't impact gameplay at all, but it does get inconvenient having to deal with log files that long.

This is for mod version 1.0.4, for game version 1.16.5, by the way

**Comment by Thresh90** [comment]
Have also ran into this issue as well, as much as I would like to provide a log, it would probably be way too large.
Makes new world creation take forever.

**Comment by Mrthomas20121** [comment]
the log spam is caused by the loot tables. if x mod is not loaded, the loot table won't load and show the errors in the log.

**Comment by Mrthomas20121** [comment]
i couldn't figure out how to not load the loot table if the mod is not loaded. so instead i just made all blocks available(even if the mod is not loaded)
